### ISSUE TITLE
Problem intergateing into Home Assistant

### ISSUE THREAD

**Issue by pgyrogear** [kohai-ut/centralite_jetstream#1]
Has anyone got Centralite Jetstream to work on there Raspberry pi5 with Home Assistant

Tried to get it installed with HACS and manually integrate in Home Assistant settings, with no luck

**Comment by kohai-ut** [comment]
I have mine running on a raspberry pi4 with home assistant. I did not use HACS to do a custom integration, I just added it directly into the filesystem folders. I wasn't aware it could be done via HACS when I put this together.

**Comment by pgyrogear** [comment]
Thank you for the response  
Can mot seem to find this folder
How would I add it to the filesystem folder. All I could find is that maybe I need to add it to configuration.yaml file but I can't figure out that either.

Any help is much appreciated.

Thanks for your Time

**Comment by kohai-ut** [comment]
This is a bit of a rough version that never got fully polished.  I can't remember if I ever tested the scenes code.  I've contemplated trying out some AI to help finish it up as my python skills are minimal.  It's been a long time since I set this up on my rpi -- this is what I have going on mine.

1. I put the github files/repo under folder:   custom_components/centralite-jestream 

Yes, I then edited yml files to customize for my setup AND there are some edits to the python code.  I do not enable ALL of my switches/loads/scenes.  I only set up those I want to show up in HA. 

2.  Edit pycentralite.py to enter the lights/loads/switches/etc numbers.  Look for LOADS_LIST, SWITCHES_LIST, ACTIVE_SCENES_DICT

3. Edit the homeassistant/configuration.yaml and add:

```
# Centralite CR for third party integration must be turned on in the Elegance system/software 
centralite-jetstream:
  # using /dev/ttyUSB0 is not persistent between boots
  port: /dev/serial/by-id/usb-FTDI_FT232R_USB_UART_AR0K8WLF-if00-port0

```

Also, I added this for visibility in the log files:
```
# Logger debugging
logger:
  default: critical
  logs:
    # log level for all python scripts
    #homeassistant.components.python_script: warning
    # jetstream
    custom_components.centralite-jetstream: critical
    custom_components.centralite-jetstream.light: critical
    custom_components.centralite-jetstream.switch: critical
    custom_components.centralite-jetstream.scene: critical  
```


I also added this:

```
homeassistant:
  auth_providers:
    - type: trusted_networks
      trusted_networks:
        - 192.168.1.0/24
    - type: homeassistant
  customize: !include centralite_desc.yaml
```


4. Ok, then create a file centralite_desc.yaml
```
  light.jsl001:
    friendly_name: "Jetstream E BEDROOM"
  light.jsl020:
    friendly_name: "Jetstream W HALL N-1-SLAV"
  light.jsl025:
    friendly_name: "Jetstream APT FAM CANS"
  light.jsl029:
    friendly_name: "Jetstream APT KITCHEN N"
  light.jsl030:
    friendly_name: "Jetstream APT KITCHEN S"
  switch.jssw00101:
    friendly_name: "Blah Switch 001"
  switch.jssw01401:
    friendly_name: "Blah Switch 014 Btn 1"
```


In my file I have both jetstream and elegance systems so this is the snippet for my jetstream that I use in HA.  The 001 in light.jsl001 is aligned with the jetstream system's ID for that light.  I have a jetstream/zigbee style dongle to communicate and configure the jetstream system and see the configuration and save it to a text file for browsing.  I assume people can figure out what the numbers should be.  Also, the documentation for jestream is available online.  

I'm happy to share my files if helpful.
